/*
 *
 * OTB-IOT - Out of The Box Internet Of Things
 *
 * Copyright (C) 2017 Piers Finlayson
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version. 
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of  MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for 
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */
 
#ifndef OTB_MAIN_BOARD_ESPI_V1_1_H_INCLUDED
#define OTB_MAIN_BOARD_ESPI_V1_1_H_INCLUDED

// Only used by hwinfo - not used directly by otb-iot (otb-iot uses via eeprom)
#ifdef OTB_HWINFO_C

#define OTB_HWINFO_MAIN_BOARD_ESPI_V1_1_GPIO_PIN_NUM       17
#define OTB_HWINFO_MAIN_BOARD_ESPI_V1_1_MODULE_NUM         1
#define OTB_HWINFO_MAIN_BOARD_ESPI_V1_1_MODULE_HDRS_NUM_1  2
#define OTB_HWINFO_MAIN_BOARD_ESPI_V1_1_MODULE_NUM_PINS_1  (40+4)
#define OTB_HWINFO_MAIN_BOARD_ESPI_V1_1_MODULE_ADDR_1      0x50

const otb_eeprom_pin_info otb_hwinfo_main_board_espi_v1_1_main_board_pin_info[OTB_HWINFO_MAIN_BOARD_ESPI_V1_1_GPIO_PIN_NUM] =
{
  // GPIO 0
  {0,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_INT_SDA,
   OTB_EEPROM_PIN_MODULE_1,
   OTB_EEPROM_PIN_FINFO_I2C_V33,
   OTB_EEPROM_PIN_PULLED_V33},

  // GPIO 1
  {1,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_TX,
   OTB_EEPROM_PIN_MODULE_1,
   OTB_EEPROM_PIN_FINFO_NONE,
   OTB_EEPROM_PIN_PULLED_FLOAT},

  // GPIO 2
  {2,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_INT_SCL,
   OTB_EEPROM_PIN_MODULE_1,
   OTB_EEPROM_PIN_FINFO_I2C_V33,
   OTB_EEPROM_PIN_PULLED_V33},

  // GPIO 3
  {3,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_RX,
   OTB_EEPROM_PIN_MODULE_1,
   OTB_EEPROM_PIN_FINFO_NONE,
   OTB_EEPROM_PIN_PULLED_FLOAT},

  // GPIO 4
  {4,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_GPIO,
   OTB_EEPROM_PIN_MODULE_3,
   OTB_EEPROM_PIN_FINFO_NONE,
   OTB_EEPROM_PIN_PULLED_V33},

  // GPIO 5
  {5,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_GPIO,
   OTB_EEPROM_PIN_MODULE_3,
   OTB_EEPROM_PIN_FINFO_NONE,
   OTB_EEPROM_PIN_PULLED_V33},

  // GPIO 6
  {6,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_RESERVED,
   OTB_EEPROM_PIN_MODULE_NONE,
   OTB_EEPROM_PIN_FINFO_RSVD_FLASH,
   OTB_EEPROM_PIN_PULLED_NA},

  // GPIO 7
  {7,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_RESERVED,
   OTB_EEPROM_PIN_MODULE_NONE,
   OTB_EEPROM_PIN_FINFO_RSVD_FLASH,
   OTB_EEPROM_PIN_PULLED_NA},

  // GPIO 8
  {8,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_RESERVED,
   OTB_EEPROM_PIN_MODULE_NONE,
   OTB_EEPROM_PIN_FINFO_RSVD_FLASH,
   OTB_EEPROM_PIN_PULLED_NA},

  // GPIO 9
  {9,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_RESERVED,
   OTB_EEPROM_PIN_MODULE_NONE,
   OTB_EEPROM_PIN_FINFO_RSVD_FLASH,
   OTB_EEPROM_PIN_PULLED_NA},

  // GPIO 10
  {10,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_RESERVED,
   OTB_EEPROM_PIN_MODULE_NONE,
   OTB_EEPROM_PIN_FINFO_RSVD_FLASH,
   OTB_EEPROM_PIN_PULLED_NA},

  // GPIO 11
  {11,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_RESERVED,
   OTB_EEPROM_PIN_MODULE_NONE,
   OTB_EEPROM_PIN_FINFO_RSVD_FLASH,
   OTB_EEPROM_PIN_PULLED_NA},

  // GPIO 12
  {12,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_GPIO,
   OTB_EEPROM_PIN_MODULE_2,
   OTB_EEPROM_PIN_FINFO_NONE,
   OTB_EEPROM_PIN_PULLED_V33},

  // GPIO 13
  {13,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_GPIO,
   OTB_EEPROM_PIN_MODULE_2,
   OTB_EEPROM_PIN_FINFO_NONE,
   OTB_EEPROM_PIN_PULLED_V33},

  // GPIO 14
  {14,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_RESET_SOFT,
   OTB_EEPROM_PIN_MODULE_1,
   OTB_EEPROM_PIN_FINFO_NONE,
   OTB_EEPROM_PIN_PULLED_V33},

  // GPIO 15
  {15,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_STATUS_LED,
   OTB_EEPROM_PIN_MODULE_1,
   OTB_EEPROM_PIN_FINFO_LED_TYPE_LED,
   OTB_EEPROM_PIN_PULLED_V0},

  // GPIO 16
  {16,
   OTB_EEPROM_PIN_HEADER_NONE,
   OTB_EEPROM_PIN_USE_RESET_HARD,
   OTB_EEPROM_PIN_MODULE_1,
   OTB_EEPROM_PIN_FINFO_NONE,
   OTB_EEPROM_PIN_PULLED_V33},
};

const otb_eeprom_pin_info otb_hwinfo_main_board_espi_v1_1_module_pin_info_1[OTB_HWINFO_MAIN_BOARD_ESPI_V1_1_MODULE_NUM_PINS_1] =
{
  // Module 1, Header 1, Pin 1
  {
    1,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_V33,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 2
  {
    2,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_V5,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 3
  {
    3,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 4
  {
    4,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_V5,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 5
  {
    5,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 6
  {
    6,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GND,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 7
  {
    7,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 8
  {
    8,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 9
  {
    9,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GND,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 10
  {
    10,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 11
  {
    11,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 12
  {
    12,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 13
  {
    13,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 14
  {
    14,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GND,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 15
  {
    15,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 16
  {
    16,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 17
  {
    17,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_V33,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 18
  {
    18,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 19
  {
    19,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 20
  {
    20,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GND,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 21
  {
    21,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 22
  {
    22,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 23
  {
    23,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 24
  {
    24,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 25
  {
    25,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_V33,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 26
  {
    26,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 27
  {
    27,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_INT_SDA,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_I2C_V33,
    OTB_EEPROM_PIN_PULLED_V33
  },

  // Module 1, Header 1, Pin 28
  {
    28,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_INT_SCL,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_I2C_V33,
    OTB_EEPROM_PIN_PULLED_V33
  },

  // Module 1, Header 1, Pin 29
  {
    29,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 30
  {
    30,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GND,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 31
  {
    31,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 32
  {
    32,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 33
  {
    33,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 34
  {
    34,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GND,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 35
  {
    35,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 36
  {
    36,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 37
  {
    37,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 38
  {
    38,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 39
  {
    39,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GND,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 1, Pin 40
  {
    40,
    OTB_EEPROM_PIN_HEADER_1,
    OTB_EEPROM_PIN_USE_GPIO,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 2, Pin 1
  {
    1,
    OTB_EEPROM_PIN_HEADER_2,
    OTB_EEPROM_PIN_USE_D_PLUS,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 2, Pin 2
  {
    2,
    OTB_EEPROM_PIN_HEADER_2,
    OTB_EEPROM_PIN_USE_D_MINUS,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_NA
  },

  // Module 1, Header 2, Pin 3
  {
    4,
    OTB_EEPROM_PIN_HEADER_2,
    OTB_EEPROM_PIN_USE_WP,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_V33
  },

  // Module 1, Header 2, Pin 4
  {
    4,
    OTB_EEPROM_PIN_HEADER_2,
    OTB_EEPROM_PIN_USE_RESET_HARD,
    OTB_EEPROM_PIN_MODULE_1,
    OTB_EEPROM_PIN_FINFO_NONE,
    OTB_EEPROM_PIN_PULLED_V33
  },

};

const otb_hwinfo_main_board_module_info otb_hwinfo_main_board_espi_v1_1_module_info[OTB_HWINFO_MAIN_BOARD_ESPI_V1_1_MODULE_NUM] =
{
  // Module 1
  {
    1,
    OTB_EEPROM_MODULE_TYPE_RPI_HAT_ESPI,
    OTB_HWINFO_MAIN_BOARD_ESPI_V1_1_MODULE_HDRS_NUM_1,
    OTB_HWINFO_MAIN_BOARD_ESPI_V1_1_MODULE_NUM_PINS_1,
    OTB_HWINFO_MAIN_BOARD_ESPI_V1_1_MODULE_ADDR_1,
    &otb_hwinfo_main_board_espi_v1_1_module_pin_info_1
  },

};

const otb_hwinfo_board_info otb_hwinfo_main_board_espi_v1_1_board_info =
{
  "espi_v1_1",
  OTB_EEPROM_HW_CODE_MAIN_BOARD,
  OTB_HWINFO_MAIN_BOARD_ESPI_V1_1_GPIO_PIN_NUM,
  OTB_HWINFO_MAIN_BOARD_ESPI_V1_1_MODULE_NUM,
  &otb_hwinfo_main_board_espi_v1_1_main_board_pin_info,
  &otb_hwinfo_main_board_espi_v1_1_module_info,
  NULL
};
#endif // OTB_HWINFO_C

#endif // OTB_MAIN_BOARD_ESPI_V1_1_H_INCLUDED
